GET http://localhost:8080/value/gauge/testGauge

### Send POST request with json body
POST http://localhost:8080/updates
Content-Type: application/json

[
  {"id": "MetricGauge", "type": "gauge", "value": 20.20},
  {"id": "MetricCounter", "type": "counter", "delta": 10}
]